name: nexunid
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:

  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  get: ^4.7.2
  get_storage: ^2.1.1
  http: ^1.5.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/img/
